### PR TITLE
Update screen more efficiently

### PR DESCRIPTION
**Pull request by txgk**

### CODE REVIEW

**Comment by txgk** [comment]
Addresses #3

**Comment by n-ivkovic** [comment]
Nice! Just one minor change before I merge this in, can you move `doupdate` into the `updateScreen` function?

Once this is merged would you be happy if #3 was closed?

**Comment by txgk** [comment]
> Nice! Just one minor change before I merge this in, can you move `doupdate` into the `updateScreen` function?

Done

**Comment by txgk** [comment]
> Once this is merged would you be happy if #3 was closed?

Let's keep it open for a while, I think there is some room left for optimizations. The flickering has decreased, but there is still a little left.

**Pull request merged**
