### PR TITLE
Use clock_gettime instead of gettimeofday to measure time

### PR DESCRIPTION
**Pull request by txgk**
POSIX.1-2008 marks gettimeofday as obsolete and clock_gettime seems to be in SUSv2 specification

### CODE REVIEW

**Comment by n-ivkovic** [comment]
Merged, good pickup!

However, while clock_gettime is in SUSv2, [CLOCK_MONOTONIC is not](https://pubs.opengroup.org/onlinepubs/007908799/xsh/time.h.html). Even in POSIX.1-2008 [CLOCK_MONOTONIC is marked as optional](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html), so I don't think it should be relied on as the sole clock.

To address this I've merged this into a separate branch and I'll make a function in common.c to get the current epoch timestamp in ms along the lines of:
```C
#ifdef CLOCK_MONOTONIC
  struct timespec sysTime;

  clock_gettime(CLOCK_MONOTONIC, &sysTime);
  result = sysTime.tv_sec * 1000 + sysTime.tv_nsec / 1000000;
#else
  /* Use gettimeofday or something else */
#endif
```
After this is done I'll merge these changes into develop, but it may be a little bit before I merge them into master. I want to do a POSIX-compliance review to make sure there isn't anything else I'm doing that's obsolete or similar, so I can address them all in one go before merging into master.

**Comment by txgk** [comment]
Oh these ifdefs always look so nasty. We can go with `CLOCK_REALTIME` which is defined in the spec you mentioned, I guess it is not a big deal. And this will save us from having to fence not very pretty ifdefs.

**Comment by n-ivkovic** [comment]
I think I'm going to stick with using `clock_gettime(CLOCK_MONOTONIC, ...)` fenced with an ifdef.

I agree ifdefs don't look great and ultimately using `CLOCK_REALTIME` wouldn't be a big deal, but now I've been reading up about monotonic clocks I believe the benefits of using it when we can outweigh making the code look a bit nicer, and I wish I'd learnt about monotonic sooner.

As of the latest commit in fix/posix-time (c879cdf6e03167382be70584392c90bbda9a304b), we get the system time like below, which I would say isn't the worst looking ifdef out there.

```C
#ifdef CLOCK_MONOTONIC
    clock_gettime(CLOCK_MONOTONIC, &sysTime);
#else
    clock_gettime(CLOCK_REALTIME, &sysTime);
#endif
```

**Comment by txgk** [comment]
Yes, in this case using monotonic clock makes more sense than using realtime one, for sure. I like this ifdef more, it's much easier to perceive :)

**Pull request merged**
